language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - "0.12"
  - "4"
  - "6"
  - "8"
  - "10"
  - "12"
  - "13"
#for ppc64le support code
jobs:
  exclude:
    - arch: ppc64le
      node_js:
        - "0.12"
