version: 2

workflows:
  version: 2
  test:
    jobs:
      - oldest-long-term-support-release
      - current-release

node-template: &node-template
  steps:
    - checkout
    - run: echo "Node version:" `node --version`
    - run: npm install
    - run:
        command: npm test
        environment:
          JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
    - run: |
        if [[ $CIRCLE_JOB == current-release ]]; then
          npm audit
        fi
    - store_test_results:
        path: reports/junit
    - store_artifacts:
        path: reports/junit

jobs:
  oldest-long-term-support-release:
    <<: *node-template
    docker:
      - image: circleci/node:6
      - image: redis

  current-release:
    <<: *node-template
    docker:
      - image: circleci/node:latest
      - image: redis
